name: Make manifest
run-name: ${{github.actor}} making manifest
on:
  push:
    branches:
      - main
jobs:
  Make-Manaifest:
    runs-on: ubuntu-latest
    steps:
      - run:  find . -path "./server/node_modules" -prune -o -path "./manifest.txt" -prune -o -path "./.git*" -prune -o -type f -print | xargs ls -l --time-style=+%d/%m%YT%H:%M:%S | awk '{print $6 " " $7}'