name: Make manifest
run-name: ${{github.actor}} making manifest
on:
  push:
    branches:
      - masterxxx
    paths-ignore:
      - 'manifest.txt'
jobs:
  Make-Manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update manifest.txt
        run:  |
          find . -path "./manifest.txt" -prune -o -path "./.git*" -prune -o -type f -print | 
          xargs ls -l --time-style=+%d/%m/%YT%H:%M:%S |
          awk '{print $6 " " substr($7, 3)}' > manifest.txt
      - run: cat manifest.txt
      - name: Checkin manifest.txt
        run: |
          git config --global user.name "alancameronwills"
          git config --global user.email "alan@cameronwills.org"
          git add manifest.txt
          git commit -m "Automatic update manifest"
          git push